name: Integration Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Integration Test
        env:
          BWCP_API_CLIENT_ID: ${{ secrets.BWCP_API_CLIENT_ID }}
          BWCP_API_CLIENT_SECRET: ${{ secrets.BWCP_API_CLIENT_SECRET }}
          BWCP_MASTER_PASSWORD: ${{ secrets.BWCP_MASTER_PASSWORD }}
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report --no-transfer-progress -Dtest=IntegrationTest

      - name: Test Coverage Report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: integration-test-coverage
          path: target/site/jacoco/